title: Minimalist Space
theme: minima


# Options: "dark", "classic", or "solarized"
minima:
  skin: dark 

# Navigation links 
header_pages:
  - README.md


# Footer links
social_links:
  github: yourusername

